name: Maze Runner tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '7.4'
            laravel-fixture: laravel51
          - php-version: '7.4'
            laravel-fixture: laravel56
          - php-version: '7.4'
            laravel-fixture: laravel58
          - php-version: '7.4'
            laravel-fixture: laravel66
          - php-version: '8.0'
            laravel-fixture: laravel8
          - php-version: '8.1'
            laravel-fixture: laravel9
          - php-version: '8.2'
            laravel-fixture: laravel10
          - php-version: '8.3'
            laravel-fixture: laravel11
          - php-version: '8.4'
            laravel-fixture: laravel11
          - php-version: '8.0'
            laravel-fixture: lumen8

    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install net-tools

    - name: install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - run: bundle exec maze-runner --no-source
      env:
        PHP_VERSION: ${{ matrix.php-version }}
        LARAVEL_FIXTURE: ${{ matrix.laravel-fixture }}
        COMPOSER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
